package com.medafrica.mavex.model.enums;
public enum AuditAction {
    LOGIN, LOGOUT, LOGIN_FAILED, PASSWORD_RESET, TOKEN_REFRESHED,
    IMPORT_EXCEL, IMPORT_ROW_SKIPPED, IMPORT_ROW_FAILED,
    ORDER_CREATED, ORDER_STATUS_CHANGED, ORDER_EMAIL_SENT, ORDER_EMAIL_FAILED, TOKEN_GENERATED, TOKEN_EXPIRED,
    PAYMENT_INITIATED, PAYMENT_SUCCESS, PAYMENT_FAILED, PAYMENT_REFUNDED,
    SMTP_CREATED, SMTP_UPDATED, SMTP_DELETED, SMTP_TESTED, SMTP_SET_DEFAULT,
    TEMPLATE_SAVED, TEMPLATE_DELETED,
    USER_CREATED, USER_ACTIVATED, USER_DEACTIVATED, USER_UPDATED,
    SYSTEM_CONFIG_UPDATED
}