# ============================================
# 000PLICATION
# ============================================
spring.application.name=mavex
server.port=1111

# ============================================
# DATABASE — MySQL
# ============================================
spring.datasource.url=jdbc:mysql://localhost:3306/mavexbd?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================
# JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ⚠️ NE PAS specifier le dialect — Hibernate le detecte automatiquement
# spring.jpa.properties.hibernate.dialect=...   ← NE PAS decommenter

# ============================================
# LOGS (optionnel — garder pour debug schema)
# ============================================
logging.level.org.hibernate.tool.schema=DEBUG
logging.level.org.hibernate.tool.schema.internal.exec=DEBUG


jwt.secret=mavex-super-secret-key-must-be-at-least-32-chars!!
jwt.access-token-expiration=90000000
#jwt.refresh-token-expiration=604800000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testing.email99f@gmail.com
spring.mail.password=hzka wzdn usju hlvc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


logging.level.org.springframework.security=DEBUG
logging.level.com.medafrica.mavex=DEBUG

# ============================================
# pour paypal 

app.base-url=http://localhost:1111
