-- ============================================================
-- AIRLINES — Préfixes IATA des compagnies aériennes mondiales
-- Source : IATA / Wikipedia / OpenFlights
-- Exécuter une seule fois : mysql -u root -p mavexbd < airlines.sql
-- ============================================================

INSERT IGNORE INTO airlines (prefix, name, iata_code, icao_code, country, mode) VALUES
-- ── AFRIQUE DU NORD ──────────────────────────────────────────
('147', 'Royal Air Maroc',              'AT',  'RAM', 'Maroc',             'AIR'),
('096', 'Air Algérie',                  'AH',  'DAH', 'Algérie',           'AIR'),
('221', 'Tunisair',                     'TU',  'TAR', 'Tunisie',           'AIR'),
('077', 'Egyptair',                     'MS',  'MSR', 'Égypte',            'AIR'),
('116', 'Afriqiyah Airways',            '8U',  'AAW', 'Libye',             'AIR'),

-- ── AFRIQUE SUBSAHARIENNE ─────────────────────────────────────
('071', 'Ethiopian Airlines',           'ET',  'ETH', 'Éthiopie',          'AIR'),
('706', 'Kenya Airways',                'KQ',  'KQA', 'Kenya',             'AIR'),
('083', 'South African Airways',        'SA',  'SAA', 'Afrique du Sud',    'AIR'),
('159', 'Air Mauritius',                'MK',  'MAU', 'Maurice',           'AIR'),
('459', 'RwandAir',                     'WB',  'RWD', 'Rwanda',            'AIR'),
('210', 'ASKY Airlines',                'KP',  'OAK', 'Togo',              'AIR'),
('197', 'Air Côte d\'Ivoire',           'HF',  'VRE', 'Côte d\'Ivoire',    'AIR'),
('168', 'Air Senegal',                  'HC',  'CSE', 'Sénégal',           'AIR'),
('253', 'Camair-Co',                    'QC',  'CMR', 'Cameroun',          'AIR'),
('232', 'Air Tanzania',                 'TC',  'ATC', 'Tanzanie',          'AIR'),
('205', 'Uganda Airlines',              'UR',  'UGA', 'Ouganda',           'AIR'),
('182', 'Air Madagascar',               'MD',  'MDG', 'Madagascar',        'AIR'),
('261', 'Zambia Airways',               'QZ',  'ZMA', 'Zambie',            'AIR'),
('195', 'Air Zimbabwe',                 'UM',  'AZW', 'Zimbabwe',          'AIR'),

-- ── MOYEN-ORIENT ─────────────────────────────────────────────
('176', 'Emirates',                     'EK',  'UAE', 'Émirats Arabes',    'AIR'),
('607', 'Etihad Airways',               'EY',  'ETD', 'Émirats Arabes',    'AIR'),
('157', 'Qatar Airways',                'QR',  'QTR', 'Qatar',             'AIR'),
('065', 'Saudi Arabian Airlines',       'SV',  'SVA', 'Arabie Saoudite',   'AIR'),
('512', 'flynas',                       'XY',  'NAS', 'Arabie Saoudite',   'AIR'),
('526', 'flydubai',                     'FZ',  'FDB', 'Émirats Arabes',    'AIR'),
('229', 'Air Arabia',                   'G9',  'ABY', 'Émirats Arabes',    'AIR'),
('229', 'Kuwait Airways',               'KU',  'KAC', 'Koweït',            'AIR'),
('072', 'Gulf Air',                     'GF',  'GFA', 'Bahreïn',           'AIR'),
('076', 'Middle East Airlines',         'ME',  'MEA', 'Liban',             'AIR'),
('512', 'Royal Jordanian',              'RJ',  'RJA', 'Jordanie',          'AIR'),
('910', 'Oman Air',                     'WY',  'OMA', 'Oman',              'AIR'),
('512', 'Jazeera Airways',              'J9',  'JZR', 'Koweït',            'AIR'),
('118', 'Iraqi Airways',                'IA',  'IAW', 'Irak',              'AIR'),
('105', 'Iran Air',                     'IR',  'IRA', 'Iran',              'AIR'),
('217', 'Air Arabia Abu Dhabi',         'GT',  'ABY', 'Émirats Arabes',    'AIR'),

-- ── EUROPE OCCIDENTALE ────────────────────────────────────────
('020', 'Lufthansa',                    'LH',  'DLH', 'Allemagne',         'AIR'),
('074', 'KLM Royal Dutch Airlines',     'KL',  'KLM', 'Pays-Bas',          'AIR'),
('125', 'British Airways',              'BA',  'BAW', 'Royaume-Uni',       'AIR'),
('057', 'Air France',                   'AF',  'AFR', 'France',            'AIR'),
('075', 'Iberia',                       'IB',  'IBE', 'Espagne',           'AIR'),
('055', 'Alitalia / ITA Airways',       'AZ',  'ITY', 'Italie',            'AIR'),
('724', 'Swiss International',          'LX',  'SWR', 'Suisse',            'AIR'),
('257', 'Austrian Airlines',            'OS',  'AUA', 'Autriche',          'AIR'),
('105', 'Finnair',                      'AY',  'FIN', 'Finlande',          'AIR'),
('117', 'SAS Scandinavian Airlines',    'SK',  'SAS', 'Suède',             'AIR'),
('328', 'Norwegian Air Shuttle',        'DY',  'NAX', 'Norvège',           'AIR'),
('082', 'Brussels Airlines',            'SN',  'BEL', 'Belgique',          'AIR'),
('047', 'TAP Air Portugal',             'TP',  'TAP', 'Portugal',          'AIR'),
('080', 'LOT Polish Airlines',          'LO',  'LOT', 'Pologne',           'AIR'),
('064', 'Czech Airlines',               'OK',  'CSA', 'Tchéquie',          'AIR'),
('235', 'Turkish Airlines',             'TK',  'THY', 'Turquie',           'AIR'),
('624', 'Pegasus Airlines',             'PC',  'PGT', 'Turquie',           'AIR'),
('555', 'Ryanair',                      'FR',  'RYR', 'Irlande',           'AIR'),
('028', 'easyJet',                      'U2',  'EZY', 'Royaume-Uni',       'AIR'),
('896', 'Wizz Air',                     'W6',  'WZZ', 'Hongrie',           'AIR'),
('980', 'Transavia',                    'HV',  'TRA', 'Pays-Bas',          'AIR'),
('997', 'Vueling Airlines',             'VY',  'VLG', 'Espagne',           'AIR'),
('068', 'Eurowings',                    'EW',  'EWG', 'Allemagne',         'AIR'),
('153', 'Aer Lingus',                   'EI',  'EIN', 'Irlande',           'AIR'),
('186', 'Croatia Airlines',             'OU',  'CTN', 'Croatie',           'AIR'),
('390', 'Aegean Airlines',              'A3',  'AEE', 'Grèce',             'AIR'),
('411', 'Air Malta',                    'KM',  'AMC', 'Malte',             'AIR'),
('018', 'Icelandair',                   'FI',  'ICE', 'Islande',           'AIR'),
('189', 'Luxair',                       'LG',  'LGL', 'Luxembourg',        'AIR'),
('781', 'Flybe',                        'BE',  'BEE', 'Royaume-Uni',       'AIR'),

-- ── EUROPE ORIENTALE ──────────────────────────────────────────
('555', 'Aeroflot',                     'SU',  'AFL', 'Russie',            'AIR'),
('555', 'S7 Airlines',                  'S7',  'SBI', 'Russie',            'AIR'),
('048', 'Ukraine International',        'PS',  'AUI', 'Ukraine',           'AIR'),
('175', 'Air Serbia',                   'JU',  'ASL', 'Serbie',            'AIR'),
('048', 'Belavia',                      'B2',  'BRU', 'Biélorussie',       'AIR'),
('530', 'TAROM',                        'RO',  'ROT', 'Roumanie',          'AIR'),
('139', 'Bulgaria Air',                 'FB',  'LZB', 'Bulgarie',          'AIR'),
('048', 'Air Astana',                   'KC',  'KZR', 'Kazakhstan',        'AIR'),
('465', 'Georgian Airways',             'A9',  'TGZ', 'Géorgie',           'AIR'),
('465', 'Armenian Airlines',            'QN',  'RME', 'Arménie',           'AIR'),

-- ── ASIE DU SUD ───────────────────────────────────────────────
('098', 'Air India',                    'AI',  'AIC', 'Inde',              'AIR'),
('526', 'IndiGo',                       '6E',  'IGO', 'Inde',              'AIR'),
('589', 'SpiceJet',                     'SG',  'SEJ', 'Inde',              'AIR'),
('140', 'Vistara',                      'UK',  'VTI', 'Inde',              'AIR'),
('285', 'Air India Express',            'IX',  'AXB', 'Inde',              'AIR'),
('612', 'SriLankan Airlines',           'UL',  'ALK', 'Sri Lanka',         'AIR'),
('214', 'Pakistan International',       'PK',  'PIA', 'Pakistan',          'AIR'),
('285', 'Biman Bangladesh Airlines',    'BG',  'BBC', 'Bangladesh',        'AIR'),

-- ── ASIE DU SUD-EST ───────────────────────────────────────────
('618', 'Singapore Airlines',           'SQ',  'SIA', 'Singapour',         'AIR'),
('160', 'Cathay Pacific',               'CX',  'CPA', 'Hong Kong',         'AIR'),
('232', 'Malaysia Airlines',            'MH',  'MAS', 'Malaisie',          'AIR'),
('126', 'Garuda Indonesia',             'GA',  'GIA', 'Indonésie',         'AIR'),
('079', 'Philippine Airlines',          'PR',  'PAL', 'Philippines',       'AIR'),
('738', 'Vietnam Airlines',             'VN',  'HVN', 'Vietnam',           'AIR'),
('145', 'Thai Airways',                 'TG',  'THA', 'Thaïlande',         'AIR'),
('607', 'AirAsia',                      'AK',  'AXM', 'Malaisie',          'AIR'),
('619', 'Scoot',                        'TR',  'TGW', 'Singapour',         'AIR'),
('455', 'Bangkok Airways',              'PG',  'BKP', 'Thaïlande',         'AIR'),
('521', 'Lion Air',                     'JT',  'LNI', 'Indonésie',         'AIR'),
('521', 'Batik Air',                    'ID',  'BTK', 'Indonésie',         'AIR'),
('738', 'VietJet Air',                  'VJ',  'VJC', 'Vietnam',           'AIR'),
('079', 'Cebu Pacific',                 '5J',  'CEB', 'Philippines',       'AIR'),

-- ── ASIE DU NORD-EST ──────────────────────────────────────────
('999', 'Air China',                    'CA',  'CCA', 'Chine',             'AIR'),
('784', 'China Eastern Airlines',       'MU',  'CES', 'Chine',             'AIR'),
('784', 'China Southern Airlines',      'CZ',  'CSN', 'Chine',             'AIR'),
('880', 'Hainan Airlines',              'HU',  'CHH', 'Chine',             'AIR'),
('131', 'Japan Airlines',               'JL',  'JAL', 'Japon',             'AIR'),
('205', 'All Nippon Airways',           'NH',  'ANA', 'Japon',             'AIR'),
('180', 'Korean Air',                   'KE',  'KAL', 'Corée du Sud',      'AIR'),
('988', 'Asiana Airlines',              'OZ',  'AAR', 'Corée du Sud',      'AIR'),
('297', 'Xiamen Airlines',              'MF',  'CXA', 'Chine',             'AIR'),
('784', 'Shenzhen Airlines',            'ZH',  'CSZ', 'Chine',             'AIR'),
('297', 'Sichuan Airlines',             '3U',  'CSC', 'Chine',             'AIR'),
('880', 'Tianjin Airlines',             'GS',  'GCR', 'Chine',             'AIR'),
('297', 'Peach Aviation',               'MM',  'APJ', 'Japon',             'AIR'),
('131', 'Jetstar Japan',                'GK',  'JJP', 'Japon',             'AIR'),
('180', 'Jeju Air',                     '7C',  'JJA', 'Corée du Sud',      'AIR'),
('988', 'Jin Air',                      'LJ',  'JNA', 'Corée du Sud',      'AIR'),
('297', 'Air Macau',                    'NX',  'AMU', 'Macao',             'AIR'),
('160', 'Hong Kong Airlines',           'HX',  'CRK', 'Hong Kong',         'AIR'),

-- ── AMÉRIQUE DU NORD ──────────────────────────────────────────
('001', 'American Airlines',            'AA',  'AAL', 'États-Unis',        'AIR'),
('006', 'Delta Air Lines',              'DL',  'DAL', 'États-Unis',        'AIR'),
('016', 'United Airlines',              'UA',  'UAL', 'États-Unis',        'AIR'),
('526', 'Southwest Airlines',           'WN',  'SWA', 'États-Unis',        'AIR'),
('279', 'JetBlue Airways',              'B6',  'JBU', 'États-Unis',        'AIR'),
('027', 'Alaska Airlines',              'AS',  'ASA', 'États-Unis',        'AIR'),
('487', 'Spirit Airlines',              'NK',  'NKS', 'États-Unis',        'AIR'),
('422', 'Frontier Airlines',            'F9',  'FFT', 'États-Unis',        'AIR'),
('014', 'Air Canada',                   'AC',  'ACA', 'Canada',            'AIR'),
('838', 'WestJet',                      'WS',  'WJA', 'Canada',            'AIR'),
('014', 'Air Transat',                  'TS',  'TSC', 'Canada',            'AIR'),
('422', 'Allegiant Air',                'G4',  'AAY', 'États-Unis',        'AIR'),
('279', 'Hawaiian Airlines',            'HA',  'HAL', 'États-Unis',        'AIR'),

-- ── AMÉRIQUE LATINE ───────────────────────────────────────────
('045', 'LATAM Airlines',               'LA',  'LAN', 'Chili',             'AIR'),
('280', 'GOL Linhas Aéreas',            'G3',  'GLO', 'Brésil',            'AIR'),
('139', 'Aeromexico',                   'AM',  'AMX', 'Mexique',           'AIR'),
('230', 'Copa Airlines',                'CM',  'CMP', 'Panama',            'AIR'),
('134', 'Avianca',                      'AV',  'AVA', 'Colombie',          'AIR'),
('280', 'Azul Brazilian Airlines',      'AD',  'AZU', 'Brésil',            'AIR'),
('937', 'Volaris',                      'Y4',  'VOI', 'Mexique',           'AIR'),
('043', 'Sky Airline',                  'H2',  'SKU', 'Chili',             'AIR'),
('043', 'Caribbean Airlines',           'BW',  'BWA', 'Trinidad',          'AIR'),
('280', 'Gol Transportes',              'G3',  'GLO', 'Brésil',            'AIR'),
('139', 'Interjet',                     '4O',  'AIJ', 'Mexique',           'AIR'),
('230', 'Air Panama',                   'AP',  'PST', 'Panama',            'AIR'),
('043', 'JetSMART',                     'JA',  'JTM', 'Chili',             'AIR'),

-- ── OCÉANIE ──────────────────────────────────────────────────
('081', 'Qantas Airways',               'QF',  'QFA', 'Australie',         'AIR'),
('652', 'Virgin Australia',             'VA',  'VOZ', 'Australie',         'AIR'),
('086', 'Air New Zealand',              'NZ',  'ANZ', 'Nouvelle-Zélande',  'AIR'),
('330', 'Jetstar Airways',              'JQ',  'JST', 'Australie',         'AIR'),
('260', 'Fiji Airways',                 'FJ',  'FJI', 'Fidji',             'AIR'),
('081', 'Rex Regional Express',         'ZL',  'RXA', 'Australie',         'AIR'),

-- ── CARGO ────────────────────────────────────────────────────
('023', 'FedEx Express',                'FX',  'FDX', 'États-Unis',        'CARGO'),
('035', 'UPS Airlines',                 '5X',  'UPS', 'États-Unis',        'CARGO'),
('020', 'Lufthansa Cargo',              'LH',  'GEC', 'Allemagne',         'CARGO'),
('172', 'Cargolux',                     'CV',  'CLX', 'Luxembourg',        'CARGO'),
('607', 'DHL Aviation',                 'D0',  'DHK', 'Allemagne',         'CARGO'),
('023', 'Atlas Air',                    '5Y',  'GTI', 'États-Unis',        'CARGO'),
('035', 'Polar Air Cargo',              'PO',  'PAC', 'États-Unis',        'CARGO'),
('618', 'Singapore Airlines Cargo',     'SQ',  'SIA', 'Singapour',         'CARGO'),
('160', 'Cathay Pacific Cargo',         'CX',  'CPA', 'Hong Kong',         'CARGO'),
('147', 'RAM Cargo',                    'AT',  'RAM', 'Maroc',             'CARGO'),
('023', 'Western Global Airlines',      'KD',  'WGN', 'États-Unis',        'CARGO'),
('999', 'Air China Cargo',              'CA',  'CAO', 'Chine',             'CARGO'),
('784', 'China Southern Cargo',         'CZ',  'CSN', 'Chine',             'CARGO'),
('172', 'IAG Cargo',                    'BA',  'BAW', 'Royaume-Uni',       'CARGO');
